### ISSUE TITLE
DESIGN: AD Details

### ISSUE THREAD

**Issue by Absolute3** [bala17o4/influencer#1]
Decide on what details the ad giver has to provide so that we can create a frontend for that and format our DB like so

**Comment by Absolute3** [comment]
![Image](https://github.com/bala17o4/influencer/assets/60956557/e547b29b-56dc-43ea-9f01-d7073eff9f8c)

First Design. Might change a few details

**Comment by bala17o4** [comment]
Ad

**Client Side**

- Company Name

- Category

- No. of Influencers

- Details

**Server Side**

- Status

- Ad Giver

**Comment by Absolute3** [comment]
We will have to modify the class either way. This looks good for a first iteration

LGTM!
